# Generated by Django 5.2.6 on 2025-10-05 08:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diario', 'Diario'), ('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pasajes_anulados', models.IntegerField(default=0)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Venta',
                'verbose_name_plural': 'Reportes de Venta',
                'db_table': 'reportes_venta',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
