# Generated by Django 5.2.6 on 2025-10-04 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres completos del pasajero', max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Apellidos completos del pasajero', max_length=100, verbose_name='Apellidos')),
                ('dni', models.CharField(db_index=True, help_text='Documento Nacional de Identidad', max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos', regex='^\\d{8}$')], verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento del pasajero', verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 9 dígitos y comenzar con 9', regex='^9\\d{8}$')], verbose_name='Teléfono Celular')),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico (opcional)', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'db_table': 'pasajeros',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['dni', 'apellidos'], name='pasajeros_dni_dc60c4_idx'), models.Index(fields=['telefono'], name='pasajeros_telefon_7c30e1_idx')],
            },
        ),
    ]
