# Generated by Django 5.2.6 on 2025-10-04 16:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasajeros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Código de Ticket')),
                ('fecha_viaje', models.DateField(db_index=True, verbose_name='Fecha de Viaje')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('origen', models.CharField(default='Lima', max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(default='Ferreñafe', max_length=100, verbose_name='Destino')),
                ('numero_asiento', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Asiento')),
                ('tipo_servicio', models.CharField(choices=[('economico', 'Económico'), ('vip', 'VIP'), ('cama', 'Semi Cama'), ('suite', 'Suite')], default='economico', max_length=20, verbose_name='Tipo de Servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio del Pasaje')),
                ('lleva_equipaje', models.BooleanField(default=False, verbose_name='Lleva Equipaje')),
                ('cantidad_maletas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Maletas')),
                ('lleva_encomienda', models.BooleanField(default=False, verbose_name='Lleva Encomienda')),
                ('descripcion_encomienda', models.TextField(blank=True, null=True, verbose_name='Descripción de Encomienda')),
                ('peso_encomienda', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso de Encomienda (kg)')),
                ('cargo_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cargo Adicional')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('usado', 'Usado'), ('anulado', 'Anulado')], db_index=True, default='vigente', max_length=20, verbose_name='Estado')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación')),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación')),
                ('monto_reembolso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Reembolso')),
                ('numero_ediciones', models.PositiveIntegerField(default=0, verbose_name='Número de Ediciones')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasajes_anulados', to=settings.AUTH_USER_MODEL, verbose_name='Anulado Por')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasajes', to='pasajeros.pasajero', verbose_name='Pasajero')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasajes_vendidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pasaje',
                'verbose_name_plural': 'Pasajes',
                'db_table': 'pasajes',
                'ordering': ['-fecha_venta'],
                'indexes': [models.Index(fields=['codigo_ticket'], name='pasajes_codigo__58ec17_idx'), models.Index(fields=['fecha_viaje', 'estado'], name='pasajes_fecha_v_bdb54b_idx'), models.Index(fields=['pasajero', 'estado'], name='pasajes_pasajer_9c9721_idx'), models.Index(fields=['-fecha_venta'], name='pasajes_fecha_v_11bb9c_idx')],
                'unique_together': {('fecha_viaje', 'hora_salida', 'numero_asiento')},
            },
        ),
    ]
