# Generated by Django 5.2.6 on 2025-10-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0001_initial'),
    ]

    operations = [
    ]
