# Generated by Django 5.2.6 on 2025-10-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0002_auto_20251005_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='codigo_ticket',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='Código de Ticket'),
        ),
    ]
