# Generated by Django 5.2.6 on 2025-11-06 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0003_alter_pasaje_codigo_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Bus')),
                ('tipo_servicio', models.CharField(choices=[('economico', 'Económico'), ('vip', 'VIP'), ('cama', 'Semi Cama'), ('suite', 'Suite')], max_length=20, verbose_name='Tipo de Servicio')),
                ('pisos', models.IntegerField(default=2, verbose_name='Número de Pisos')),
                ('total_asientos', models.IntegerField(default=60, verbose_name='Total de Asientos')),
                ('asientos_piso1', models.IntegerField(default=12, verbose_name='Asientos Piso 1')),
                ('asientos_piso2', models.IntegerField(default=48, verbose_name='Asientos Piso 2')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Bus',
                'verbose_name_plural': 'Configuraciones de Buses',
                'db_table': 'configuracion_buses',
            },
        ),
        migrations.CreateModel(
            name='AsientoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje', models.DateField(db_index=True, verbose_name='Fecha de Viaje')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('origen', models.CharField(default='Lima', max_length=100)),
                ('destino', models.CharField(default='Ferreñafe', max_length=100)),
                ('numero_asiento', models.IntegerField(verbose_name='Número de Asiento')),
                ('piso', models.IntegerField(default=1, verbose_name='Piso')),
                ('ocupado', models.BooleanField(db_index=True, default=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('pasaje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_reservado', to='pasajes.pasaje')),
            ],
            options={
                'verbose_name': 'Asiento de Viaje',
                'verbose_name_plural': 'Asientos de Viaje',
                'db_table': 'asientos_viaje',
                'indexes': [models.Index(fields=['fecha_viaje', 'hora_salida', 'ocupado'], name='asientos_vi_fecha_v_6f246c_idx'), models.Index(fields=['fecha_viaje', 'hora_salida', 'origen', 'destino'], name='asientos_vi_fecha_v_6370c4_idx')],
                'unique_together': {('fecha_viaje', 'hora_salida', 'origen', 'destino', 'numero_asiento')},
            },
        ),
    ]
