# Generated by Django 5.2.6 on 2025-11-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0004_configuracionbus_asientoviaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientoviaje',
            options={'ordering': ['fecha_viaje', 'piso', 'numero_asiento'], 'verbose_name': 'Asiento de Viaje', 'verbose_name_plural': 'Asientos de Viaje'},
        ),
        migrations.AlterUniqueTogether(
            name='asientoviaje',
            unique_together={('fecha_viaje', 'hora_salida', 'origen', 'destino', 'piso', 'numero_asiento')},
        ),
    ]
